; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-p4-evboard]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-p4-evboard
framework = arduino
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
lib_deps = 
	lvgl/lvgl@^9.3
build_flags = 
	-DBOARD_HAS_PSRAM
	-O3
	-DCORE_DEBUG_LEVEL=1
	-I include/
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=0
	-DARDUINO_USB_MSC_ON_BOOT=0
	-DARDUINO_USB_DFU_ON_BOOT=0
	-DCONFIG_LV_USE_PPA=y
	-DCONFIG_SPIRAM_SPEED_200M=y
	-DCONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_360
	-DCONFIG_LV_ATTRIBUTE_FAST_MEM_USE_IRAM=y
	-DCONFIG_COMPILER_OPTIMIZATION_PERF=y




